[package]
name = "test-aarch64-only"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
multiversed = { path = "../..", default-features = false, features = [
    "arm64",
    "arm64-v2",
    "arm64-v3",
] }
multiversion = "0.8"
